### ISSUE TITLE
Ignoring parameter "winbind trusted domains only"

### ISSUE THREAD

**Issue by noelmcloughlin** [saltstack-formulas/samba-formula#62]
This line in pillar.example is no longer valid.

```
Unknown parameter encountered: "winbind trusted domains only"
Ignoring unknown parameter "winbind trusted domains only"
Unknown parameter encountered: "winbind trusted domains only"
Ignoring unknown parameter "winbind trusted domains only"
```

**Comment by sebma** [comment]
@noelmcloughlin What is the new parameter equivalent to `winbind trusted domains only`, is it `allow trusted domains = yes` ?

**Comment by noelmcloughlin** [comment]
Hi, I'm not sure we would have to look up samba documentation, as formula
only should pass what samba winbind understands, it should be documented by
them

**Comment by sebma** [comment]
@noelmcloughlin You're right, found it in the wiki of Samba : https://wiki.samba.org/index.php/Samba_4.8_Features_added/changed#vfs_aio_linux_module_removed

They say `winbind trusted domains only` has been removed in Samba v4.8.0 .
