### ISSUE TITLE
Ignoring parameter "winbind trusted domains only" - 

### ISSUE THREAD

**Issue by spirritus** [saltstack-formulas/samba-formula#64]
defaults.yaml still contains the parameter: winbind trusted domains only

Unknown parameter encountered: "winbind trusted domains only"
Ignoring unknown parameter "winbind trusted domains only"

"fix(defaults): remove obsolete parameter #63" did only remove half the necessary lines.

**Comment by myii** [comment]
Thanks for the report @spirritus.  #63 appears to be limited to removing `allow trusted domains` only.  I haven't looked into this much but I've found the following references:

* https://lists.samba.org/archive/samba-technical/2017-December/124265.html
* https://gitlab.com/search?group_id=&project_id=3456094&repository_ref=master&scope=commits&search=winbind+trusted+domains+only

So it does appear to be removed.  Would you care to provide a PR for this?

**Comment by spirritus** [comment]
Deleting line 55 "winbind trusted domains only: no" in defaults.yaml seems to do the trick.
